### ISSUE TITLE
Buildilng fails on Node v0.11.11

### ISSUE THREAD

**Issue by moll** [bloodhound/syslog-stream#3]
Hey,

Doing `node-gyp rebuild` in the module's folder fails with the following:

```
  CXX(target) Release/obj.target/syslog/syslog.o
../syslog.cc:10:33: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
static Handle<Value> open(const Arguments& args) {
                                ^~~~~~~~~
                                v8::internal::Arguments
/Users/user/.node-gyp/0.11.11/deps/v8/include/v8.h:141:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../syslog.cc:20:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
static Handle<Value> close(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/user/.node-gyp/0.11.11/deps/v8/include/v8.h:141:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../syslog.cc:27:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
static Handle<Value> write(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/user/.node-gyp/0.11.11/deps/v8/include/v8.h:141:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../syslog.cc:40:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "close", close);
  ^~~~~~~~~~~~~~~
/Users/user/.node-gyp/0.11.11/src/node.h:163:25: note: expanded from macro
      'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/user/.node-gyp/0.11.11/src/node.h:152:13: note: candidate function [with
      TypeName = v8::Handle<v8::Object>] not viable: no known conversion from
      'int (int)' to 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../syslog.cc:41:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "write", write);
  ^~~~~~~~~~~~~~~
/Users/user/.node-gyp/0.11.11/src/node.h:163:25: note: expanded from macro
      'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/user/.node-gyp/0.11.11/src/node.h:152:13: note: candidate function [with
      TypeName = v8::Handle<v8::Object>] not viable: no known conversion from
      'ssize_t (int, const void *, size_t)' to 'v8::FunctionCallback' (aka
      'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
5 errors generated.
make: *** [Release/obj.target/syslog/syslog.o] Error 1
```

Let me know if you need any more intel. Thanks! :-)

**Comment by jeffcarp** [comment]
This might be a Node 11.11 incompatibility error. It looks like the same issue is happening here: 
- https://github.com/mscdex/mmmagic/issues/16
- http://stackoverflow.com/questions/21721964/bcrypt-not-installing-on-ubuntu

It's probably not helpful for fixing your exact problem, but this comment from Rod Vagg sheds more light:

"FYI if you're using any native addons anywhere in your app and insist on running 0.11 then you might want to skip 0.11.11 and wait for 0.11.12 as native addon compiles are broken for this release."
https://groups.google.com/d/msg/nodejs/o8o7V_Nit3s/EBmSDKF08GwJ

**Comment by moll** [comment]
Thanks for the fairly prompt reply. Yeah, quite certainly a changed API issue.

Anyways, I decided to see how to write native modules myself and wrote a bare-bones working Syslog binding for v0.11 myself. Once I test it on Linux, I'll OSS it as well. :-)

**Comment by robertrossmann** [comment]
Just tested the build on Travis and Node 0.11.13 -> still fails, although the errors seem to be a bit different.

Not sure how to fix these as my C skills are almost non-existent, so I am posting here for your reference in case you would like to investigate this further and, possibly, fix these somehow. Thanks!

```
make: Entering directory `/home/travis/build/Dreamscapes/Logful/node_modules/syslog-stream/build'
CXX(target) Release/obj.target/syslog/syslog.o
../syslog.cc:10:33: error: ‘Arguments’ does not name a type
../syslog.cc:10:44: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../syslog.cc: In function ‘v8::Handle<v8::Value> open(const int&)’:
../syslog.cc:11:9: error: invalid types ‘const int[int]’ for array subscript
../syslog.cc:12:24: error: invalid types ‘const int[int]’ for array subscript
../syslog.cc:17:15: error: too few arguments to function ‘v8::Handle<v8::Boolean> v8::True(v8::Isolate*)’
/home/travis/.node-gyp/0.11.13/deps/v8/include/v8.h:6559:17: note: declared here
../syslog.cc: At global scope:
../syslog.cc:20:34: error: ‘Arguments’ does not name a type
../syslog.cc:20:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../syslog.cc: In function ‘v8::Handle<v8::Value> close(const int&)’:
../syslog.cc:23:20: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
/home/travis/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: declared here
../syslog.cc: At global scope:
../syslog.cc:27:34: error: ‘Arguments’ does not name a type
../syslog.cc:27:45: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../syslog.cc: In function ‘v8::Handle<v8::Value> write(const int&)’:
../syslog.cc:28:24: error: invalid types ‘const int[int]’ for array subscript
../syslog.cc:29:35: error: invalid types ‘const int[int]’ for array subscript
../syslog.cc:34:20: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
/home/travis/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: declared here
../syslog.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../syslog.cc:39:39: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [5], v8::Handle
v8::Value> (&)(const int&))’
../syslog.cc:39:39: note: candidate is:
/home/travis/.node-gyp/0.11.13/src/node.h:194:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&,
const char*, v8::FunctionCallback)
../syslog.cc:40:41: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], 
unresolved overloaded function type>)’
../syslog.cc:40:41: note: candidate is:
/home/travis/.node-gyp/0.11.13/src/node.h:194:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&,
const char*, v8::FunctionCallback)
../syslog.cc:41:41: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], 
unresolved overloaded function type>)’
../syslog.cc:41:41: note: candidate is:
/home/travis/.node-gyp/0.11.13/src/node.h:194:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&,
const char*, v8::FunctionCallback)
../syslog.cc: At global scope:
../syslog.cc:20:22: warning: ‘v8::Handle<v8::Value> close(const int&)’ defined but not used [-Wunused-function]
../syslog.cc:27:22: warning: ‘v8::Handle<v8::Value> write(const int&)’ defined but not used [-Wunused-function]
make: *** [Release/obj.target/syslog/syslog.o] Error 1
make: Leaving directory `/home/travis/build/Dreamscapes/Logful/node_modules/syslog-stream/build'
```

**Comment by moll** [comment]
@Alaneor: If you need, I've got a v0.10 and v0.11 compatible Syslog binding at https://github.com/moll/node-syslogh. :-)

**Comment by jeffcarp** [comment]
Thanks @moll, @Alaneor I would use that repo if possible.

**Comment by alexmingoia** [comment]
Pull requests are welcome...
